version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "admin"]
    volumes:
      - redis-data:/data

  app:
    build: .
    container_name: webhook_service
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://dev:test@mongo:27017"
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: "admin"
    depends_on:
      - mongo
      - redis

volumes:
  mongo-data:
  redis-data:
